### ISSUE TITLE
Hi, I ran docker-compose with this configuration

### ISSUE THREAD

**Issue by Ara041285** [Ara041285/github-slideshow#2]
Hi, I ran docker-compose with this configuration

```
version: '3'
services:
  weblate:
    ports:
      - 127.0.0.1:6372:8080
    environment:
      WEBLATE_SITE_DOMAIN: *******
      WEBLATE_ADMIN_NAME : reza
      WEBLATE_ADMIN_PASSWORD: *********
      WEBLATE_ADMIN_EMAIL: **********@gmail.com

```

But when I try to login or register, I get this error

![Screenshot from 2021-04-28 15-28-24](https://user-images.githubusercontent.com/32940427/116395103-ee06f380-a838-11eb-8a58-e62bc5f207b9.png)

Is there a problem with the configuration or is the problem somewhere else?

__Originally posted by @rezarazani in https://github.com/WeblateOrg/weblate/issues/5936__
